apiVersion: apps/v1
kind: Deployment
metadata:
  name: gva-server
  annotations:
    strategy.spinnaker.io/versioned: "false"
    app.kubernetes.io/version: 0.0.1
  labels:
    app: gva-server
    version: gva-vue3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gva-server
      version: gva-vue3
  template:
    metadata:
      labels:
        app: gva-server
        version: gva-vue3
    spec:
      containers:
        - name: activity-backend
          # 修改项目
          image: juben/backend/activity-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
              name: http
          volumeMounts:
            # 修改项目
            - mountPath: /go/src/backend/project-config/config.docker.yaml
              name: gvaconfig
              subPath: config.docker.yaml
            - mountPath: /etc/localtime
              name: localtime
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: gvaconfig
          configMap:
            name: gvaconfig
      imagePullSecrets:
        - name: coding-docker
